//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation
    {
        public Accommodation()
        {
            this.CommentAccommodations = new HashSet<CommentAccommodation>();
            this.LikeAccommodations = new HashSet<LikeAccommodation>();
        }
    
        public int AccommodationID { get; set; }
        public int UserID { get; set; }
        public string TypeOfAccommodation { get; set; }
        public int NumberofRooms { get; set; }
        public double NumberofPeoplePerRoom { get; set; }
        public string DistancetoCampus { get; set; }
        public string WIFI { get; set; }
        public double Price { get; set; }
        public string Comment { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string MainImage { get; set; }
        public string RoomImage { get; set; }
        public string KitchenImage { get; set; }
        public string BathroomImage { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual ICollection<CommentAccommodation> CommentAccommodations { get; set; }
        public virtual ICollection<LikeAccommodation> LikeAccommodations { get; set; }
    }
}
