//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.CommentBooks = new HashSet<CommentBook>();
            this.LikeBooks = new HashSet<LikeBook>();
        }
    
        public int BookID { get; set; }
        public int UserID { get; set; }
        public string BookName { get; set; }
        public string Edition { get; set; }
        public string Course { get; set; }
        public string neworused { get; set; }
        public string Image { get; set; }
        public double Price { get; set; }
        public string Comment { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual ICollection<CommentBook> CommentBooks { get; set; }
        public virtual ICollection<LikeBook> LikeBooks { get; set; }
    }
}
