//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PIKUPEntities : DbContext
    {
        public PIKUPEntities()
            : base("name=PIKUPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book> Books { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<SkillsTalent> SkillsTalents { get; set; }
        public DbSet<Transport> Transports { get; set; }
        public DbSet<Accommodation> Accommodations { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
        public DbSet<CommentAccommodation> CommentAccommodations { get; set; }
        public DbSet<LikeAccommodation> LikeAccommodations { get; set; }
        public DbSet<CommentService> CommentServices { get; set; }
        public DbSet<LikeService> LikeServices { get; set; }
        public DbSet<CommentBook> CommentBooks { get; set; }
        public DbSet<LikeBook> LikeBooks { get; set; }
        public DbSet<CommentProduct> CommentProducts { get; set; }
        public DbSet<LikeProduct> LikeProducts { get; set; }
        public DbSet<CommentTransport> CommentTransports { get; set; }
        public DbSet<LikeTransport> LikeTransports { get; set; }
        public DbSet<CommentSkillTalent> CommentSkillTalents { get; set; }
        public DbSet<LikeSkillsTalent> LikeSkillsTalents { get; set; }
    }
}
