//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CommentProducts = new HashSet<CommentProduct>();
            this.LikeProducts = new HashSet<LikeProduct>();
        }
    
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public string Productname { get; set; }
        public string Categoryname { get; set; }
        public string NeworUsed { get; set; }
        public string ProductImage { get; set; }
        public double NumberofItem { get; set; }
        public double ProductPrice { get; set; }
        public string Comment { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual ICollection<CommentProduct> CommentProducts { get; set; }
        public virtual ICollection<LikeProduct> LikeProducts { get; set; }
    }
}
