//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.CommentServices = new HashSet<CommentService>();
            this.LikeServices = new HashSet<LikeService>();
        }
    
        public int ServiceID { get; set; }
        public int UserID { get; set; }
        public string Typeofservice { get; set; }
        public string ServiceImage { get; set; }
        public double Serviceprice { get; set; }
        public string Comment { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual ICollection<CommentService> CommentServices { get; set; }
        public virtual ICollection<LikeService> LikeServices { get; set; }
    }
}
