//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillsTalent
    {
        public SkillsTalent()
        {
            this.CommentSkillTalents = new HashSet<CommentSkillTalent>();
            this.LikeSkillsTalents = new HashSet<LikeSkillsTalent>();
        }
    
        public int skillandtalentID { get; set; }
        public int UserID { get; set; }
        public string TypeofskillORtalent { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }
        public string Song { get; set; }
        public string Comment { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual ICollection<CommentSkillTalent> CommentSkillTalents { get; set; }
        public virtual ICollection<LikeSkillsTalent> LikeSkillsTalents { get; set; }
    }
}
