//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public Transport()
        {
            this.CommentTransports = new HashSet<CommentTransport>();
            this.LikeTransports = new HashSet<LikeTransport>();
        }
    
        public int TransportationID { get; set; }
        public int UserID { get; set; }
        public string DepartureDestination { get; set; }
        public string ArrivalDestination { get; set; }
        public string DepartureDate { get; set; }
        public string Image { get; set; }
        public double NumberOfPassengers { get; set; }
        public double Price { get; set; }
        public string Comment { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual ICollection<CommentTransport> CommentTransports { get; set; }
        public virtual ICollection<LikeTransport> LikeTransports { get; set; }
    }
}
