//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIK_UP_REST_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public UserTable()
        {
            this.Accommodations = new HashSet<Accommodation>();
            this.Books = new HashSet<Book>();
            this.Products = new HashSet<Product>();
            this.SkillsTalents = new HashSet<SkillsTalent>();
            this.Transports = new HashSet<Transport>();
            this.Services = new HashSet<Service>();
            this.CommentAccommodations = new HashSet<CommentAccommodation>();
            this.LikeAccommodations = new HashSet<LikeAccommodation>();
            this.CommentServices = new HashSet<CommentService>();
            this.LikeServices = new HashSet<LikeService>();
            this.CommentBooks = new HashSet<CommentBook>();
            this.LikeBooks = new HashSet<LikeBook>();
            this.CommentProducts = new HashSet<CommentProduct>();
            this.LikeProducts = new HashSet<LikeProduct>();
            this.CommentTransports = new HashSet<CommentTransport>();
            this.LikeTransports = new HashSet<LikeTransport>();
            this.CommentSkillTalents = new HashSet<CommentSkillTalent>();
            this.LikeSkillsTalents = new HashSet<LikeSkillsTalent>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int StudentNumber { get; set; }
        public string Gender { get; set; }
        public string Institution { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Accommodation> Accommodations { get; set; }
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<SkillsTalent> SkillsTalents { get; set; }
        public virtual ICollection<Transport> Transports { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<CommentAccommodation> CommentAccommodations { get; set; }
        public virtual ICollection<LikeAccommodation> LikeAccommodations { get; set; }
        public virtual ICollection<CommentService> CommentServices { get; set; }
        public virtual ICollection<LikeService> LikeServices { get; set; }
        public virtual ICollection<CommentBook> CommentBooks { get; set; }
        public virtual ICollection<LikeBook> LikeBooks { get; set; }
        public virtual ICollection<CommentProduct> CommentProducts { get; set; }
        public virtual ICollection<LikeProduct> LikeProducts { get; set; }
        public virtual ICollection<CommentTransport> CommentTransports { get; set; }
        public virtual ICollection<LikeTransport> LikeTransports { get; set; }
        public virtual ICollection<CommentSkillTalent> CommentSkillTalents { get; set; }
        public virtual ICollection<LikeSkillsTalent> LikeSkillsTalents { get; set; }
    }
}
